gicp_relocalization_node:
  ros__parameters:
    # General Configuration
    mode: "initial_guess" # Options: "multi_guess", "initial_guess"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/2026rmuc.pcd"
    target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/111.pcd"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/hotel.pcd"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/2026rmul.pcd"
    map_frame: "map"
    visualization_en: true
    source_cloud_topic: "/cloud_registered_dense"
    alignment_frequency: 5.0
    accumulate_frames: 3
    tf_publish_frequency: 30.0
    # Convergence Criteria (small_gicp score, lower is better)
    gicp:
      score_threshold: 200.0
      target_voxel_leaf_size: 0.05
      source_voxel_leaf_size: 0.05  # -1.0 means no downsampling
      max_correspondence_distance: 0.5
      max_iterations: 100
      transformation_epsilon: 0.01
      euclidean_fitness_epsilon: 0.01
    converged_count_threshold: 2

    # Continuous low-frequency relocalization
    enable_continuous_relocalization: true
    max_tracking_lost_count: 3
    continuous_relocalization:
      max_translation_jump: 0.1  # meter
      max_yaw_jump: 0.1         # rad

    timeout_seconds: 5.0  # 超时时间（秒）
    # default_pose_on_timeout: [5.0, 7.0, 0.0, 0.0, 0.0, 0.0]  # 超时后发布的默认位姿
    default_pose_on_timeout: [6.8, 3.9, 0.0, 0.0, 0.0, 0.0]  # 超时后发布的默认位姿

    # Initial Pose (x, y, z, roll, pitch, yaw) - Used if mode is "initial_guess"
    initial_pose: [6.8, 3.9, 0.0, 0.0, 0.0, 0.0]
    # initial_pose: [7.3, 3.5, 0.0, 0.0, 0.0, 0.0]
    # initial_pose: [5.0, 7.0, 0.0, 0.0, 0.0, 0.4]
    # Multi-Guess Parameters
    multi_guess:
      search_rectangles: [0.0, 3.0, 0.0, 3.0, -2.0, 0.0, -1.0, 1.0]
      z_candidates: [0.0, 0.4]
      step_x: 2.0
      step_y: 2.0
      step_yaw: 0.785398

    # Height Filter (PassThrough on z) - optional performance optimization
    height_filter:
      enable: true
      min_z: 0.0
      max_z: 6.5

    # Source Crop Parameters
    source_crop:
      enable: true
      min_x: -8.0
      max_x: 8.0
      min_y: -8.0
      max_y: 8.0
      min_z: -0.5
      max_z: 6.0
