gicp_relocalization_node:
  ros__parameters:
    # General Configuration
    mode: "initial_guess" # Options: "multi_guess", "initial_guess"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/rmuc.pcd"
    target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/111.pcd"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/hotel.pcd"
    # target_pcd_file: "src/navigation/navi2_bringup/maps/pcd/rmul.pcd"
    map_frame: "map"
    visualization_en: true
    source_cloud_topic: "/livox/stdpc"
    alignment_frequency: 1.0
    accumulate_frames: 3
    tf_publish_frequency: 30.0
    # Convergence Criteria
    overlap_threshold: 0.65
    converged_count_threshold: 2

    # Continuous low-frequency relocalization
    enable_continuous_relocalization: true
    max_tracking_lost_count: 3

    timeout_seconds: 5.0  # 超时时间（秒）
    default_pose_on_timeout: [6.0, 3.4, 0.0, 0.0, 0.0, 0.0]  # 超时后发布的默认位姿
    
    # Initial Pose (x, y, z, roll, pitch, yaw) - Used if mode is "initial_guess"
    initial_pose: [7.3, 3.5, 0.0, 0.0, 0.0, 0.0]
    # initial_pose: [5.0, 7.0, 0.0, 0.0, 0.0, 0.4]
    # Multi-Guess Parameters
    multi_guess:
      search_rectangles: [0.0, 3.0, 0.0, 3.0, -2.0, 0.0, -1.0, 1.0]
      z_candidates: [0.0, 0.4]
      step_x: 2.0
      step_y: 2.0
      step_yaw: 0.785398

    # Height Filter (PassThrough on z) - optional performance optimization
    height_filter:
      enable: true
      min_z: 0.0
      max_z: 2.5

    # Source Crop Parameters
    source_crop:
      enable: true
      min_x: -5.0
      max_x: 5.0
      min_y: -5.0
      max_y: 5.0
      min_z: -0.5
      max_z: 2.5

    # GICP Parameters
    gicp:
      target_voxel_leaf_size: 0.05
      source_voxel_leaf_size: 0.05
      max_correspondence_distance: 0.5
      max_iterations: 100
      transformation_epsilon: 0.001
      euclidean_fitness_epsilon: 0.001
