lidar_merger_node:
  ros__parameters:
    front_topic: "/livox/lidar_192_168_1_135"
    back_topic: "/livox/lidar_192_168_1_122"
    merged_topic: "/livox/lidar"
    merged_frame_id: "livox_frame"
    qos_depth: 5
    best_effort: true
    sync_queue_size: 10
    max_sync_interval_ms: 5.0
    publish_pointcloud: false
    front_cloud_topic: "/livox/front_cloud"
    back_cloud_topic: "/livox/back_cloud"
    merged_cloud_topic: "/livox/lidar_cloud"
    extrinsic_back_to_front: [0.0, 0.4, 0.0, -0.35453, 0.0, 0.0] # x, y, z, roll, pitch, yaw (in radians)
