#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║            pclfilter 系统诊断工具                               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

source /opt/ros/humble/setup.bash

echo "【1】检查ROS2节点状态..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ros2 node list | grep -E "clear_node|rviz"
echo ""

echo "【2】检查点云话题..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ /cloud_registered 话题"
ros2 topic info /cloud_registered 2>/dev/null | head -3

echo ""
echo "✓ /cloud_filter_baselink 话题"
ros2 topic info /cloud_filter_baselink 2>/dev/null | head -3
echo ""

echo "【3】采样点云数据..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "原始点云样本："
timeout 1 ros2 topic echo /cloud_registered --no-arr 2>/dev/null | head -20
echo ""

echo "【4】故障排除建议..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "如果在RViz2中看不到点云，请按以下步骤操作："
echo ""
echo "【步骤A】配置固定坐标框架"
echo "   1. 打开RViz2窗口"
echo "   2. 左侧找到 'Global Options'"
echo "   3. 点击 'Fixed Frame' 的下拉框"
echo "   4. 改为 'camera_init'"
echo "   5. 按回车确认"
echo ""
echo "【步骤B】添加原始点云"
echo "   1. 点击左下方绿色 'Add' 按钮"
echo "   2. 点击 'By topic' 标签"
echo "   3. 找到 '/cloud_registered'"
echo "   4. 点击右侧 'PointCloud2' 选项"
echo "   5. 点击 'Add' 按钮"
echo "   → 应该看到白色点云"
echo ""
echo "【步骤C】添加过滤点云"
echo "   1. 点击左下方 'Add' 按钮"
echo "   2. 点击 'By topic' 标签"
echo "   3. 找到 '/cloud_filter_baselink'"
echo "   4. 点击右侧 'PointCloud2' 选项"
echo "   5. 点击 'Add' 按钮"
echo "   → 应该看到绿色点云"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 诊断完成!"
echo ""
echo "提示："
echo "  • 点云数据在正常发布"
echo "  • 确保RViz2的'Fixed Frame'设为'camera_init'"
echo "  • 使用 'By topic' 方式添加显示（不是 'By display type'）"
echo "  • 如有问题，查看: /TROUBLESHOOTING.md"
echo ""
