#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           pclfilter RViz2 点云可视化快速指南                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ 以下节点已在后台运行："
echo "   1. clear_node (过滤点云)"
echo "   2. rviz2 (可视化工具)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 RViz2 配置步骤："
echo ""
echo "【第一步】设置坐标系参考框架"
echo "   1. 在RViz2左侧面板找到 'Global Options' 组件"
echo "   2. 找到 'Fixed Frame' 下拉框"  
echo "   3. 将其改为 'camera_init'"
echo ""
echo "【第二步】添加原始点云显示 (白色点)"
echo "   1. 点击RViz2左下方的 'Add' 按钮"
echo "   2. 在弹出框中选择 'By topic' 标签页"
echo "   3. 从列表中找到 '/cloud_registered'"
echo "   4. 点击它右侧的 'PointCloud2' 类型"
echo "   5. 点击 'Add' 按钮"
echo "   ✓ 应该看到白色的点云出现在RViz2中心"
echo ""
echo "【第三步】添加过滤后的点云显示 (绿色点)"
echo "   1. 再次点击 'Add' 按钮"
echo "   2. 选择 'By topic' 标签页"
echo "   3. 从列表中找到 '/cloud_filter_baselink'"
echo "   4. 点击它右侧的 'PointCloud2' 类型"
echo "   5. 点击 'Add' 按钮"
echo "   ✓ 应该看到绿色的点云出现（比白色点云少30个点）"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 预期效果对比："
echo ""
echo "  【/cloud_registered】(原始点云)"
echo "     总数: 130个点"
echo "     分布: 后方50个 + 中间30个(在过滤区) + 前方50个"
echo "     颜色: 白色"
echo ""
echo "  【/cloud_filter_baselink】(过滤后点云)"
echo "     总数: 100个点 ✓"
echo "     分布: 后方50个 + 中间0个(已移除) + 前方50个"
echo "     颜色: 绿色/彩色"
echo ""
echo "  ✨ 过滤效果：移除了机器人本体区域内的30个点"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 交互控制:"
echo "   • 鼠标中键 + 拖动  → 旋转视角"
echo "   • 鼠标滚轮        → 缩放"
echo "   • 鼠标右键 + 拖动  → 平移"
echo ""
echo "⚙️  调整点云显示大小:"
echo "   1. 在左侧 'Displays' 面板找到点云显示"
echo "   2. 展开它，找到 'Size (m)' 参数"
echo "   3. 调整数值（推荐0.05-0.1）"
echo ""
echo "🔍 调试命令:"
echo "   # 查看正在运行的话题"
echo "   ros2 topic list"
echo ""
echo "   # 查看点云数据频率"
echo "   ros2 topic hz /cloud_registered"
echo "   ros2 topic hz /cloud_filter_baselink"
echo ""
echo "   # 查看点云数据细节"
echo "   ros2 topic echo /cloud_registered --no-arr | head -20"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 功能验证完成!"
echo ""
echo "如有问题，请查看以下文件："
echo "   • RVIZ2_VISUALIZATION_GUIDE.md - 详细配置指南"
echo "   • config/cube.yaml - 过滤区域配置"
echo ""
echo ""
