euclidean_cluster_node:
  ros__parameters:
    topics:
      input: /cloud_registered_dense
      output: /clustered_obstacles

    cluster:
      z_min: 0.05
      z_max: 0.6
      max_detection_range: 10.0
      leaf_size: 0.05
      cluster_tolerance: 0.2
      min_cluster_size: 15
      max_cluster_size: 500

    tracker:
      match_distance_threshold: 0.5
      max_missed_frames: 3
      dynamic_speed_threshold: 0.2
