euclidean_cluster_node:
  ros__parameters:
    topics:
      input: /filtered_points_no_ground
      output: /detected_bounding_boxs

    cluster:
      z_min: 0.15
      z_max: 0.6
      leaf_size: 0.05
      min_cluster_size: 15
      max_cluster_size: 1000
      seg_distances: [5.0, 10.0, 15.0, 20.0]
      cluster_distances: [0.15, 0.20, 0.25, 0.30]

    tracker:
      match_distance_threshold: 0.5
      max_missed_frames: 3
      dynamic_speed_threshold: 0.2
