gicp_relocalization_node:
  ros__parameters:
    # OTHER 
    use_initial_alignment: true
    target_pcd_file: "src/icp_relocalization/maps/rmuc.pcd"
    base_frame: "base_link"
    map_frame: "map"
    drift_threshold_m: 1.0
    drift_threshold_rad: 0.5
    icp_frequency: 1.0
    feature_k_search: 10
    publish_pose_on_odom: true
    alignment_frequency: 1.0
    map_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accumulate_frames: 5

    # GICP
    gicp:
      target_voxel_leaf_size: 2.0
      source_voxel_leaf_size: 2.0
      max_correspondence_distance: 10.0
      max_iterations: 100
      transformation_epsilon: 0.01
      euclidean_fitness_epsilon: 0.01

    # SAC-IA
    sac_ia:
      min_sample_distance: 0.5
      correspondence_randomness: 6
      num_samples: 3
      max_correspondence_distance: 1.0
